### ISSUE TITLE
Tip mistakenly calls Rihn a spell

### ISSUE THREAD

**Issue by Ads20000** [davewx7/citadel#122]
![screenshot from 2017-10-21 00-50-25](https://user-images.githubusercontent.com/3178485/31845561-e149fa82-b5f9-11e7-9dd7-fec89725e34f.png)
Third training game, discard one Rihn when prompted then hold onto the other one, the tip calls Rihn a spell when it's actually a creature.

**Comment by davewx7** [comment]
Fixed!
