### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by eugeneloza** [davewx7/citadel#125]
Trying to download DLC:
> CRITICAL:   ./bin/anura : module::client::on_response(std::string)+0xad7
> CRITICAL:   ./bin/anura : std::_Function_handler<void (std::string), std::_Bind<std::_Mem_fn<void (module::client::*)(std::string)> (module::client*, std::_Placeholder<1>)> >::_M_invoke(std::_Any_data const&, std::string)+0x3b
> CRITICAL:   ./bin/anura : std::function<void (std::string)>::operator()(std::string) const+0x26
> CRITICAL:   ./bin/anura : http_client::handle_receive(std::shared_ptr<http_client::Connection>, boost::system::error_code const&, unsigned long)+0xddb
> CRITICAL:   ./bin/anura : boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, std::_Bind<std::_Mem_fn<void (http_client::*)(std::shared_ptr<http_client::Connection>, boost::system::error_code const&, unsigned long)> (http_client*, std::shared_ptr<http_client::Connection>, std::_Placeholder<1>, std::_Placeholder<2>)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long)+0x10a
> CRITICAL:   ./bin/anura : boost::asio::detail::task_io_service::poll(boost::system::error_code&)+0x154
> CRITICAL:   ./bin/anura : http_client::process()+0x73b
> CRITICAL:   ./bin/anura : module::client::process()+0x3a
> CRITICAL:   ./bin/anura() [0xa24ed5]
> CRITICAL:   ./bin/anura : UTILITY_update_launcher(std::vector<std::string, std::allocator<std::string> > const&)+0x337
> CRITICAL:   ./bin/anura : test::run_utility(std::string const&, std::vector<std::string, std::allocator<std::string> > const&)+0x126
> CRITICAL:   ./bin/anura : main()+0x2e36
> CRITICAL:   /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf5
> CRITICAL:   ./bin/anura() [0x6abcc5]
> CRITICAL: ---
> Aborted

![2017-10-22-093616_1366x768_scrot](https://user-images.githubusercontent.com/10726162/31858938-a3e40d18-b70c-11e7-9c76-08f298c63472.png)

Can this be "low on HDD space" problem?

**Comment by eugeneloza** [comment]
Full console output:
[aa.txt](https://github.com/davewx7/citadel/files/1404661/aa.txt)
700Mb still free on HDD so shouldn't be a HDD free space issue.

**Comment by eugeneloza** [comment]
Yes, this definitely looks like a HDD space issue (1.4 Gb free space is not enough)
Another screenshot:

![2017-10-22-094825_1366x768_scrot](https://user-images.githubusercontent.com/10726162/31859129-f6ba284e-b70f-11e7-90f3-497f17aa0786.png)

**Comment by eugeneloza** [comment]
Yes, 100% clear it's the HDD space issue. Everything went fine with 2+Gb of free space on HDD. Looks like the game needs ~1.5-1.8 Gb to install (download DLC).

**Comment by sapientN3T** [comment]
closing per gs' request
