### ISSUE TITLE
Alt+Tab on Ubuntu 17.10

### ISSUE THREAD

**Issue by Ads20000** [davewx7/citadel#126]
Alt+Tab on Ubuntu 17.10 (with Ubuntu's modified GNOME session on Wayland) doesn't work. It leaves a bar at the top showing the desktop background and clicking results in clicking the part of the UI a few pixels below the actual mouse cursor.

![screenshot from 2017-10-22 22-42-14](https://user-images.githubusercontent.com/3178485/31867643-523cfbc6-b78b-11e7-9799-f6f972b598e3.png)

**Comment by davewx7** [comment]
If you run the game with --fullscreen-exclusive does that modify things at all?

**Comment by Ads20000** [comment]
0AD doesn't work either (well, the unofficial snap doesn't) so may be a wider issue (probably with games in general and Wayland)...

`sh run.sh --fullscreen-exclusive` yields `ERROR: main.cpp:698 : unrecognized arg: '--fullscreen-exclusive`

**Comment by Ads20000** [comment]
Scratch that - Alt + Tab doesn't work on for these games on X11 either.

This is a bug in GNOME 3.26, see [here](https://bugzilla.gnome.org/show_bug.cgi?id=788493) for the upstream bug and see [here](https://bugs.launchpad.net/mutter/+bug/1725649) for progress for fixing the bug in Ubuntu 17.10 and 18.04.

**Comment by Ads20000** [comment]
The workaround for now is to go to AA's settings and uncheck fullscreen, then restart the game.
