### ISSUE TITLE
Assertion failure when using Flesh Golem's Remake after using Dark Emissary's Dark Sacrifice on it

### ISSUE THREAD

**Issue by leper** [davewx7/citadel#136]
This is somewhat of a race condition, but if you are fast enough to select the Flesh Golem after using Dark Sacrifice on it, to be able to select/click on remake you get an assertion failure.

This seems unexpected, it would be better if this was just silently ignored since there is nothing valid that can be done.

modules/citadel/data/classes/game_state.cfg:357 where creature != null, which in this case is violated as the Flesh Golem was already destroyed.

**Comment by davewx7** [comment]
Fixed; thank you for the report!
