### ISSUE TITLE
Incorrect animation location for redirected spells

### ISSUE THREAD

**Issue by jollki** [davewx7/citadel#137]
Spells that are redirected by Eji's Cunning play their animations over the old target instead of the new one. In multiplayer matches this only affects the player who cast the original spell, not the player who cast the redirect.

Here's a test-case to demonstrate.  Just cast the spells and watch where the animations play.

>https://pastebin.com/z4W473hs

	{
		name: 'ejis-animation',
	
	
	text: '',
	set: 'core',
	avatar: 'eji-the-summoner.png',
	portrait: 'eji-the-summoner.png',
	portrait_scale: 0.2,
	portrait_translate: [0,0],
	enemy_name: 'Eji',
	skip_mulligan: true,
	player_deck: ['Knife in the Dark','Fireball','Obliterate'],
	setup_commands: "map(players, set(value.base_income, 100)) + map(players, set(value.resources, 100))",
	bot_args: {
		deck: "[string] :: [q(Eji's Cunning)]*20",
	},

	starting_units: [
		
	  { card_name: 'Skeleton',
	    loc: [1,0],
	    controller: 0,
	  },
	
	{
		card_name: 'Wraith',
		loc: [2,0],
		controller: 0,
	},

	{
		card_name: 'Ilz Apprentice',
		loc: [2,4],
		controller: 1,
	},
	
	{
	  card_name: 'Skeleton',
	  loc: [3,0],
	  controller: 0,
	},

	],
	},

**Comment by davewx7** [comment]
Fixed. Thank you for the test case!
