### ISSUE TITLE
Switch drop down disappears when clicking Archives in Library

### ISSUE THREAD

**Issue by crabel** [davewx7/citadel#163]
Minor bug:

Go to Library
Note that there is a dropdown allowing to switch between different sets like Core, Scum of Marlak, Experimental, ...
Click on archives
Click back
Result: Dropdown is gone
Expected result: Dropdown is there

**Comment by galegosimpatico** [comment]
This had an easy fix I already pushed.

With the next game update the issue should get fixed.

Thanks!
