### ISSUE TITLE
Eji's Cunning in response to Anthem of Battle crashes the game

### ISSUE THREAD

**Issue by crabel** [davewx7/citadel#174]
The opponent just cast "Anthem of Battle" and I tried to cast "Eji's Cunning" in response. That caused an assertion.
[crashlog.txt](https://github.com/davewx7/citadel/files/1544897/crashlog.txt)
![screenshot from 2017-12-09 18 35 35](https://user-images.githubusercontent.com/5255626/33797914-3cc5f2e8-dd10-11e7-877b-43daf32c3e64.png)

Btw. the assertion window size is quite large on my machine (Linux Mint, Cinnamon desktop).
![screenshot from 2017-12-09 18 34 03](https://user-images.githubusercontent.com/5255626/33797879-ace58c24-dd0f-11e7-98ac-b1c9dd247637.png)

I guess, "mass spells" are not eligible targets for that spell.

**Comment by davewx7** [comment]
I have fixed this in https://github.com/davewx7/citadel/commit/8c6567f82569b1fa4da3190105ed81b8dfae4bb8

The fix will ship in the next update.
