### ISSUE TITLE
Possible bug: Hailstorm affects creatures under "Cover"

### ISSUE THREAD

**Issue by crabel** [davewx7/citadel#175]
Shouldn't creatures under cover be immune to spells? But casting Hailstorm still damages them.

**Comment by davewx7** [comment]
Creatures with Cover are not immune to spells. They cannot be *targeted* by enemy spells. That is, any spell which uses the word "target" cannot have an enemy creature with Cover as the target. However, Hailstorm doesn't use the word target in its rules text and it doesn't have any targets when cast. As such, Hailstorm interacts with creatures with Cover in the same way as it interacts with any other creature.

**Comment by galegosimpatico** [comment]
There is a game doc with part of the rules, even though is _game_ data (just to be printed, but _game_ data), it is really nicely readable: https://github.com/davewx7/citadel/blob/8c6567f82569b1fa4da3190105ed81b8dfae4bb8/data/help-abilities.cfg#L13
Good reread (I caught an error there recently).
