### ISSUE TITLE
Crippling graphics bugs (mac?)

### ISSUE THREAD

**Issue by Velensk** [davewx7/citadel#18]
So when I first reported this issue on github I hadn't actually explored how bad it got. The graphics become more and more messed up as play continues in some ways which are hard to capture with the free screenshot program I have. I'm inclined to assume these are specific to the mac version as if not somebody would already have reported this.

The pictures below in order are:
1: Game starts, screen is fine.
2: A card is played or discarded, things start getting strange.
3: Additional discard or play is made, things get worse.
4: The enemy takes a turn. Game becomes practically unplayable.

Other notes:
-Once the players hand disappears one can still mouse over them and the information pop up for them can still be seen.
-Although the pass button is not visible on the enemy turn it can still be pressed.
-The corners in particular seem to spawn a lot of odd graphics.

![1good](https://cloud.githubusercontent.com/assets/6527245/6942871/6b095308-d858-11e4-892d-ced4bbe403e4.jpeg)
![2afterdiscard](https://cloud.githubusercontent.com/assets/6527245/6942873/6dca4db8-d858-11e4-8a10-dfc7225f8693.jpeg)
![3nextdiscard](https://cloud.githubusercontent.com/assets/6527245/6942874/6fe71310-d858-11e4-832f-fae478ceb95b.jpeg)
![4enemyturnjpeg](https://cloud.githubusercontent.com/assets/6527245/6942877/71c61f6e-d858-11e4-8a12-caa563ada3be.jpg)

**Comment by davewx7** [comment]
This is all fixed now I think.
