### ISSUE TITLE
Assertion failed when adding Tremors to a deck

### ISSUE THREAD

**Issue by sarimak** [davewx7/citadel#180]
Assertion failed when trying to add newly purchased Tremors to an existing deck.
Looks like Tremors do not have properly set image because the assertion refers to a file images/portraits/card-size/null

formula.cpp:230
cairo.cpp:1860
modules/gui/data/objects/scrollable_pane.cfg 137

See the screenshot for full error message.

**Comment by sarimak** [comment]
![screenshot_2018-01-11_17-47-18](https://user-images.githubusercontent.com/5323684/34836460-3dd1f342-f6f8-11e7-9a33-6b9450dc6462.png)

**Comment by galegosimpatico** [comment]
Welcome to the bug tracker! Thanks for reporting!

https://github.com/davewx7/citadel/commit/56ccb0fa3359eee8d88662a3d83527bec3e1ebca should fix the issue.
