### ISSUE TITLE
`Outsmart the Guards` allows capturing `Oldric's Trap`

### ISSUE THREAD

**Issue by leper** [davewx7/citadel#204]
If you placed Oldric's Trap, and it has enough charge for an enemy that is approaching, but the trap itself is occupied by one of your creatures, and the enemy then uses Outsmart the Guards, he both exchanges the places of both creatures, but his creature also captures the trap instead of triggering it.

Expected behaviour: Oldric's Trap triggers, since the enemy creature entered it, albeit in a slightly unusual way.

**Comment by galegosimpatico** [comment]
Game design issues are _de facto_ attended and commented at [the Argentum Age Discord server](https://discord.gg/0s6mSoZ1vJPlvcIw). I expect shorter process times there.

**Comment by sapientN3T** [comment]
Outsmart the Guards should be using creature.set_loc instead of setting creature.loc directly.

Currently it looks like set_loc won't be able to handle the animation hint though... that also needs to be addressed.
