### ISSUE TITLE
Army of One Heart doesn't work correctly

### ISSUE THREAD

**Issue by Lucius4** [davewx7/citadel#206]
This spell from experimental set doesn't work as expected.

Player is forced to target both friendly and enemy creatures in chain and they all get an attack and life bonus.

Description of the card says that only friendly creatures should be targeted and obtain the bonus.

**Comment by galegosimpatico** [comment]
> [...]
> Player is forced to target both friendly and enemy creatures in chain [...]
> [...]

I think it used to be like that but not now. See in this picture:

![https://frupic.frubar.net/shots/36753.png](https://frupic.frubar.net/shots/36753.png)
[https://frupic.frubar.net/36753](https://frupic.frubar.net/36753)

There is a `Cast` button under the card. It allows to close the targeting _loop_ before every targetable has been targeted.

> [...]
> Description of the card says that only friendly creatures should be targeted and obtain the bonus.

That's right, and I think that's bug.

**Comment by galegosimpatico** [comment]
> [...]
> 
> Description of the card says that only friendly creatures should be targeted and obtain the bonus.

It should be fixed by now. Thanks!

:smiley:
