### ISSUE TITLE
License

### ISSUE THREAD

**Issue by saniv** [davewx7/citadel#22]
What is the license? Otherwise it is as good as closed sourced:
https://help.github.com/articles/open-source-licensing/
>Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

i.e. anyone copying and/or using it will be breaking law, the same way as Windows or Photoshop.

**Comment by davewx7** [comment]
Good point, we added a LICENSE file detailing our licensing!
