### ISSUE TITLE
Assertion failed error occurred when I started game first time and downloaded file.

### ISSUE THREAD

**Issue by ransl0t** [davewx7/citadel#235]
![error](https://user-images.githubusercontent.com/41484624/43013976-9da3ee56-8c85-11e8-9b66-0dd75a79b944.PNG)

My computer is Windows 10 (64-bit). And my HDD storage is 229GB(external hard drive).

**Comment by galegosimpatico** [comment]
Is that _reliable_ domestic broadband? Or _far_ or _cluttered_ shared WiFi?

Happened only once, or it is still happening every time?

**Comment by ransl0t** [comment]
It happened every time. And network worked well.

**Comment by ransl0t** [comment]
![error2](https://user-images.githubusercontent.com/41484624/43027730-ee7b5b9e-8cb6-11e8-8061-34dc3e1bfda0.PNG)
I deleted and started game several times. This error always occurred. Sometimes game could be playing even it did, but other assertion failed error occurred when I played campaign.

**Comment by galegosimpatico** [comment]
This definitely looks like a similar case we could sort out by downloading `sounds/` manually.

Because your network was reliable, that increases suspicion the content got corrupted at the assets server.

If with the next content update this goes away, then it could have been caused by a somehow errored updates upload.

Normally I would now want to force 1.0.684 as an exact copy of the 1.0.683 assets, but there's no reliable way to do this for 1.0.683 exceptionally, so updates will have to wait for the next Steam deployment.

**Comment by galegosimpatico** [comment]
> [...] Error on first comment always occurred. [...]

That or similar errors at the assets download have been sighted ever since the last content update.

This could be a launcher bug, but it has not been changed, therefore must be either an obscure launcher bug hidden until current update, or offending content at the assets server, or both.

**Comment by Fealthas** [comment]
Can confirm, get same two errors on win10. Unable to play a single game. Something with installation seems completely broken.

**Comment by galegosimpatico** [comment]
I could reproduce it over the week, but can't look in detail until next weekend.

While this doesn't get a fix, I can give you troubleshooting support for it at [the Discord server](
https://discord.gg/0s6mSoZ1vJPlvcIw). Basically if I remember correctly we know that one of the people who get caught by this was able to play once we helped a manual download of the `sounds/` subset of the assets.

**Comment by pshem** [comment]
I got the same error on Linux(Peppermint 8, based on Ubuntu 16.04), when running the game for the first time, at the end of asset download. It finished installation succesfully on the second run. I used the standalone installer from the website.

**Comment by mandeville-school** [comment]
Ubuntu 18.04 fresh download today and installation resulted in the same error:
"**Assertion failed**
compress.cpp:109 ASSERTION FAILED: FAILED TO DECOMPRESS 0 BYTES OF DATA TO EXPECTED 0 BYTES: result = -2 (-Z_OK = 0) OUTPUT 0"
Argentum Age splash updater shows:
"Installing game files: 2239/2659" at that point and I can confirm there are no music or sound folders created. 

The game can then be started by rerunning run.sh but there's no sound (yep!) and single player crashes with no ambient sound file requests failing. See post above for folder layout but at the point I've noted all these details I also see "update-cache" folder. All file date/timestamps 2017 Sep/Oct apart from the "aa" folder created by the Installer being run.

**Comment by galegosimpatico** [comment]
> In my installation directory, there are no /sounds or /music folders, both of which are probably guilty for the lack of music or sound. Should I submit a trace of running the program?

I see no reason for submitting it, but thanks!

**Comment by pshem** [comment]
Last few lines shown in the terminal when the game crashes:
```
ERROR: sound.cpp:759 : Could not load sound: sounds/ambient/amb_breakthrough_puzzle.wav Couldn't open sounds/ambient/amb_breakthrough_puzzle.wav
CRITICAL: sound.cpp:1324 ASSERTION FAILED: Could not load wave: ambient/amb_breakthrough_puzzle.wav

CRITICAL: 
---
CRITICAL: stack trace:
CRITICAL:   ./anura : sound::process()+0x38a
CRITICAL:   ./anura : Level::process()+0x176
CRITICAL:   ./anura : LevelRunner::play_cycle()+0x3367
CRITICAL:   ./anura : LevelRunner::play_level()+0x174
CRITICAL:   ./anura : main()+0x68b1
CRITICAL:   /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf0
CRITICAL:   ./anura() [0x6ad3b5]
CRITICAL: ---
INFO: asserts.cpp:85 : ATTEMPTING TO SEND CRASH REPORT...
./anura.sh: line 3: 14143 Aborted                 LD_LIBRARY_PATH=./runtime:$LD_LIBRARY_PATH ./anura "$@"
```

**Comment by mandeville-school** [comment]
For the record manually copying all the sounds & music folders into the root folder fixed the problem for me.

btw, found out about your excellent game because of a preview of Valve's upcoming card game. I'm sure you know all about it!! Just thinking it would be a shame for you not to captialise on that (yours is free after all) because the installer's not working. Soon as it's fixed I'm recommending to my gaming group.

Good luck and love the game,

**Comment by pshem** [comment]
@mandeville-school Yeah, we must have read the same comments under the Gaming on Linux article. https://www.gamingonlinux.com/articles/valves-digital-card-game-artifact-to-release-november-28th-with-linux-support.12263/comment_id=129464

**Comment by mandeville-school** [comment]
@pshem. Yep. A real find :+1:

**Comment by galegosimpatico** [comment]
https://github.com/davewx7/citadel/blob/7c6c2885f307281ab7f436e2d087c400bfa41545/data/news.cfg#L9
