### ISSUE TITLE
Sun hieroglyph bug

### ISSUE THREAD

**Issue by cronvel** [davewx7/citadel#33]
How to reproduce it:
* Build a dawn obelisk
* Add the sun hieroglyph on it

Unexpected results:
* The sun hieroglyph heals adjacent allies AND ennemies
* You cannot use 'Smite the Defiler' on the lane anymore
* Allies that spawn on this lane doesn't get the focused light bonus

**Comment by Velensk** [comment]
Are you sure that you were in control of the obelisk when you enchanted it?

I've just tested this and I'm not getting any of the unexpected behavior you describe, however the behavior you describe would occur if the obelisk had been captured.

**Comment by cronvel** [comment]
You are right, I didn't know that obelisk could be captured, sorry :S 
That small white triangle is hard to see!
