### ISSUE TITLE
Game crash after trying to play "Rihn's Crusader".

### ISSUE THREAD

**Issue by cronvel** [davewx7/citadel#64]
Hi,

That's the 3rd time the game crash exactly when I clicked a "Rihn's Crusader" to play it.
Here is the console log:

```
CRITICAL: cairo.cpp:1311 ASSERTION FAILED: SVG rendering error painting images/portraits/card-size/rihns-crusader.png: out of memory

CRITICAL: At /home/cedric/.citadel//dlc/citadel/data/classes/citadel.cfg 217:
fbo: c.render(ww, hh, cmd, m),
     ^-----------------------^

At /home/cedric/.citadel//dlc/citadel/data/objects/creature.cfg 838:
lib.citadel.render_frame(c, w, h,
^

At /home/cedric/.citadel//dlc/citadel/data/objects/creature.cfg 138:
set(animation, render_image(anim_w, anim_h))
               ^---------------------------^
```

OS: Linux (up to date Fedora)

**Comment by davewx7** [comment]
Does it happen 100% of the time when you try to play Rihn's Crusader? Does it happen only with this card?

You can reproduce the problem quickly by using the debug console. Press ctrl+d to bring up the console. Type debug_card("Rihn's Crusader") -- it will give you this card in your hand. Type debug_mana(10) to give yourself plenty of mana to play it. then try playing it. Does it happen if you play it right at the start of a game?

Does it always have the same error message?

I tried and couldn't immediately reproduce it -- can play Rihn's Crusader without problems.

What OS are you on?

**Comment by cronvel** [comment]
Hi, in fact it happens in the library too: I can't scroll down in my deck, whenever the "Rihn's Crusader" is about to be displayed, the game crash with that error.
It happens 100% of time (done 6 time in a row).

I'm running an up to date Linux Fedora, with an up to date game.

It seems related to the card display, not the card rule. It only happens with this card.

**Comment by davewx7** [comment]
Okay, that seems really very strange. Are you building the Anura engine from source? If you are can you please try pulling latest (I just added a change) and trying again? It should give me some more details on where the problem is.

**Comment by cronvel** [comment]
Erf, it's late now! ^^ 

I will try to download and build Anura tomorrow, but I don't know how to plug Argentum Age in it.
Can you give me a link to the howto?

**Comment by davewx7** [comment]
It's okay, I've updated the Anura binaries you're using (I expect you're using the auto-updating Anura?) So just try running again and tell me what error you get now.

**Comment by cronvel** [comment]
Hi, 

Maybe another potential bug, but I was unable to auto-update Anura engine yesterday: while the game updated fine, Anura's update always timed out. This morning both Anura and Citadel get updated correctly, so here is what I got after choosing the card:

```
INFO: formula_function.cpp:3927 : CONSOLE: 'SPAWN CARDS IN HAND'
INFO: ShadersOGL.cpp:1292 : Added shader: arrow_render
INFO: formula_function.cpp:3927 : CONSOLE: 'SPAWN CARDS IN HAND'
INFO: formula_function.cpp:3927 : CONSOLE: 'SPAWN CARDS IN HAND'
incorrect gamma=(0/100000)
CRITICAL: cairo.cpp:1321 ASSERTION FAILED: SVG rendering error painting images/portraits/card-size/rihns-crusader.png: out of memory

CRITICAL: At /home/cedric/.citadel//dlc/citadel/data/classes/citadel.cfg 217:
fbo: c.render(ww, hh, cmd, m),
     ^-----------------------^

At /home/cedric/.citadel//dlc/citadel/data/objects/creature.cfg 838:
lib.citadel.render_frame(c, w, h,
^

At /home/cedric/.citadel//dlc/citadel/data/objects/creature.cfg 138:
set(animation, render_image(anim_w, anim_h))
               ^---------------------------^


---
CRITICAL: stack trace:
CRITICAL:   ./anura() [0x85ee2b3]
CRITICAL:   ./anura : graphics::execute_cairo_ops(graphics::cairo_context&, variant)+0x87
CRITICAL:   ./anura : graphics::execute_cairo_ops(graphics::cairo_context&, variant)+0xa3
CRITICAL:   ./anura : graphics::execute_cairo_ops(graphics::cairo_context&, variant)+0xa3
CRITICAL:   ./anura() [0x85daa0b]
CRITICAL:   ./anura() [0x85daf63]
CRITICAL:   ./anura : variant::operator()(std::vector<variant, std::allocator<variant> > const&) const+0xfeb
CRITICAL:   ./anura() [0x8819a99]
CRITICAL:   ./anura() [0x881f74e]
CRITICAL:   ./anura() [0x8805604]
CRITICAL:   ./anura : game_logic::Formula::execute(game_logic::FormulaCallable const&) const+0x90
CRITICAL:   ./anura : variant::operator()(std::vector<variant, std::allocator<variant> > const&) const+0xd9a
CRITICAL:   ./anura() [0x8819a99]
CRITICAL:   ./anura() [0x8805604]
CRITICAL:   ./anura : game_logic::Formula::execute(game_logic::FormulaCallable const&) const+0x90
CRITICAL:   ./anura : variant::operator()(std::vector<variant, std::allocator<variant> > const&) const+0xd9a
CRITICAL:   ./anura() [0x8819a99]
CRITICAL:   ./anura() [0x887c897]
CRITICAL:   ./anura() [0x8805604]
CRITICAL:   ./anura() [0x88194ac]
CRITICAL:   ./anura() [0x87fb2c0]
CRITICAL:   ./anura() [0x8805604]
CRITICAL:   ./anura : game_logic::FormulaExpression::evaluate(game_logic::FormulaCallable const&) const+0x32
CRITICAL:   ./anura() [0x887b08c]
CRITICAL:   ./anura : game_logic::Formula::execute(game_logic::FormulaCallable const&) const+0x90
CRITICAL:   ./anura : CustomObject::handleEventInternal(int, game_logic::FormulaCallable const*, bool)+0x355
CRITICAL:   ./anura : CustomObject::handleEvent(int, game_logic::FormulaCallable const*)+0x188
CRITICAL:   ./anura : Level::process_draw()+0xd1
CRITICAL:   ./anura : LevelRunner::play_cycle()+0x1e7d
CRITICAL:   ./anura : LevelRunner::play_level()+0xa9
CRITICAL:   ./anura : main()+0x6fee
CRITICAL:   /lib/libc.so.6 : __libc_start_main()+0xf5
CRITICAL:   ./anura() [0x827091d]
CRITICAL: ---
INFO: asserts.cpp:72 : ATTEMPTING TO SEND CRASH REPORT...
INFO: stats.cpp:129 : SENT 1122/1122
ERROR: http_client.cpp:321 : ERROR IN HTTP RECEIVE: (2(End of file), )
ERROR: http_client.cpp:323 : Error no such file or directory
INFO: stats.cpp:123 : UPLOAD COMPLETE: ERROR RECEIVING DATA
./anura.sh: line 3:  5804 Aborted                 (core dumped) LD_LIBRARY_PATH=./runtime ./anura $@
```

The crash always happens when the card is about to be played, i.e. selected and moved on the left sidebar. I hope it helps.

**Comment by davewx7** [comment]
This is really, really strange that it crashes on this specific card but on nothing else. Can you try replacing the rihns-crusader.png (there are two of them -- citadel/images/portraits/card-size/rihns-crusader.png and citadel/images/portraits/rihns-crusader.png ) files simply with other files from the same directory and see if it works? Perhaps there is something strange about the image that is causing it to fail.

**Comment by cronvel** [comment]
Wow, that's strange: you're right.
After replacing both png by "Rihn's Anointed", the bug disappear.
Restoring the original png produces the bug again.

I wonder why it only affects my system/computer.

**Comment by rborch** [comment]
Hi! I experience the exact same behaviour when selecting Rhin's Crusader in the library.
https://i.imgur.com/lihCEEE.png
I also replaced it by "rhins-anointed.png", which "fixed" it. Importing rhins-crusader.png in GIMP and reexporting it, has the same effect.

Therefore there could be something wrong with the original png which the image loading routines can not handle correctly (?)

**Comment by galegosimpatico** [comment]
Greetings @rborch, thanks for the insights. I have reverted the image `images/portraits/card-size/rihns-crusader.png` to its previous version, so if you do a fresh boot of the game any time from now, the game should be updating itself and I hope the game wouldn't be crashing then.

**Comment by rborch** [comment]
I reverted the image back to its original before updating and confirmed, that the game still crashes on selecting Rhins Crusader. After updating however, it did not crash anymore.

Therefore the bug (or its symptoms) are resolved, I guess.

**Comment by galegosimpatico** [comment]
Yes, here is consensus it is largely more cost effective just replacing the
image and get back to :yellow_heart::black_heart::green_heart::heart::blue_heart:.

The current working theory is that there is a bug in some C/C++ dependency the
game uses, not in any game code.

Thanks again both @rborch and @cronvel,

**Comment by cronvel** [comment]
@galegosimpatico You're welcome ;)
