### ISSUE TITLE
"Player is queuing for multiplayer" message, but that player is me :p

### ISSUE THREAD

**Issue by cbeck88** [davewx7/Citadel#8]
I got confused at some points because it would tell me that a player was queuing for multiplayer when there wasn't anyone else, or when I was the only one on the server. I think what happened was that it got a delayed message that I myself was in the queue.

It would be nice if either the client would tell me the name of the player who is queuing, or if it would just suppress messages referring to my own queuing status.

**Comment by davewx7** [comment]
This should be fixed not to happen now! It will also tell you the name of the queued player.
