### ISSUE TITLE
Crash with "Bus Error"

### ISSUE THREAD

**Issue by cbeck88** [davewx7/citadel#9]
Got this while playing Velensk's rats scenario:

CONSOLE: ['YYY GOT game message state id = ', 178, 30944]
CONSOLE: 'timing_message: state id = 178 took 20ms server 11ms'
CONSOLE: ['HAVE PLAYER DAMAGE: ', [0, 0]]
CONSOLE: 'game updated'
CONSOLE: 'SET NEW STATE'
CONSOLE: ['SPAWN: ', 3, 0, false]
CONSOLE: 'SPAWN CREATURE: Ratman Sniper'
CONSOLE: 'request_updates: 178'
XX tbs_send: 1426980427
HANDLE MESSAGE ((({
	"state_id": 178,
	"type": "request_updates"
})))
XXX: @4838168 player 0 confirm sync 178
BOT: @4838214 GOT RESPONSE: message_received
BOT: handle message @ 4838215 : message_received... ( {
	"game_type": "citadel",
	"id": 1426976373,
	"log": "",
	"nplayer": 1,
	"players": ["iceiceice","King Snixex"],
	"server_time": 11,
	"started": false,
	"state": "@eval deserialize('0x8d9d329a6d9941a')",
	"state_id": 178,
	"type": "game"
} )
Bus error
chris@chris-KLR650 ~/anura-src/anura $

**Comment by davewx7** [comment]
That sounds bad. Have you been able to reproduce it at all? can you maybe turn core dumps on and try to get a core dump of it?

**Comment by cbeck88** [comment]
I just got it again on the same scenario. I wasn't really doing anything in particular, it was after the scenario got fairly populated...

I'm going to try running through gdb I think and see if it happens again.

CONSOLE: ['YYY GOT game message state id = ', 255, 44255]
CONSOLE: 'timing_message: state id = 255 took 20ms server 8ms'
CONSOLE: ['HAVE PLAYER DAMAGE: ', [0, 4]]
CONSOLE: 'game updated'
CONSOLE: 'SET NEW STATE'
CONSOLE: ['SPAWN: ', 14, 0, false]
CONSOLE: 'request_updates: 255'
XX tbs_send: 1426981342
HANDLE MESSAGE ((({
	"state_id": 255,
	"type": "request_updates"
})))
XXX: @1650722 player 0 confirm sync 255
BOT: @1650856 GOT RESPONSE: message_received
BOT: handle message @ 1650857 : message_received... ( {
	"game_type": "citadel",
	"id": 1426981327,
	"log": "",
	"nplayer": 1,
	"players": ["iceiceice","King Snixex"],
	"server_time": 8,
	"started": false,
	"state": "@eval deserialize('0x79a791edb243428')",
	"state_id": 255,
	"type": "game"
} )
Bus error

**Comment by cbeck88** [comment]
Playing same scenario, got a seemingly similar crash:

"Out of memory: Kill process or sacrifice child"

This killed my desktop session and I had to log back in and restart all programs. I was even running Anura through gdb this time! I didn't realize that gdb was not sandboxed such that this can't happen.

**Comment by davewx7** [comment]
Interesting. Do you happen to know if the process was using large amounts of memory for long before it died like this?

I would tend to imagine there is some bug causing a sudden explosion of memory consumption. Hard to say what exactly without more info :(

**Comment by cbeck88** [comment]
I guess I wasn't monitoring the memory consumption. I'm not extremely knowledgeable about linux -- if there's more ways that I can get useful info I would be happy to try, but I didn't find a core dump, and gdb didn't seem to help. There was a noticeable point where the process began to freeze and the mouse moved very slowly on the screen -- in principle I could have tried to interrupt and get a backtrace but at that point I couldn't tab out of the full screen.

**Comment by cbeck88** [comment]
I reproduced the Out of Memory crash again. This time it was actually caught by gdb and didn't bring down my system -- maybe I forgot to run in gdb the first time? I'm pretty sure I did though...

Here's contents of terminal with gdb:
http://pastebin.com/dKvt9NrU

**Comment by cbeck88** [comment]
One more time, similar scenario. This time, the game became quite "laggy" presumably from high memory consumption, during an AI turn near the end of the scenario. However this didn't bring down the program, instead I was able to finish the scenario with victory. Nevertheless, performance remained poor, and when I transitioned to the library screen, that was where it crashed instead with the same Out of Memory.

http://pastebin.com/MahtUDm2

This suggests to me that it might not have to do specifically with Citadel, that it might be a memory leak in Anura? Maybe there is something wrong with garbage collection?

**Comment by davewx7** [comment]
Is this always during the rats scenario?

How much free memory do you have on your machine? e.g. if you type free -m on the terminal what does it show?

Do you play with the scenario going for a particularly long time before crashing?

**Comment by cbeck88** [comment]
chris@chris-KLR650 ~/anura-src/anura $ free -m
             total       used       free     shared    buffers     cached
Mem:          3524       1038       2486        201          1        288
-/+ buffers/cache:        749       2775
Swap:         3661       1588       2073

Yeah, it only crashes in my experience after its been going a long time. I didn't observe it except related to the rats scenario, although it did happen shortly after the rats scenario also.

**Comment by cbeck88** [comment]
Ok, this time I was able to make a video of the behavior just before it crashed... it basically crashed before I could look at memory consumption stats. But at least there is something which is possibly useful -- one of the cards in my hand could be moused over, but not properly selected or played, and when I would scroll to a different card, it wouldn't get "undrawn".

Video: https://drive.google.com/file/d/0B54Q-3UjP5fidVQzbTNnNEFSR00/view?usp=sharing
Console log of crash: 
http://pastebin.com/HqUm46TF
